name: HerokuCI
on:
  push:
    branches:
      - master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Heroku 
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: add remote
      run: git remote add heroku https://git.heroku.com/${HEROKU_BACKEND_APP_NAME}.git
      env:
        HEROKU_BACKEND_APP_NAME: ${{secrets.HEROKU_BACKEND_APP_NAME}}
    - name: login heroku 
      run: echo -e "machine api.heroku.com\n\tlogin ${EMAIL}\n\tpassword ${HEROKU_API_KEY}\nmachine git.heroku.com\n\tlogin ${EMAIL}\n\tpassword ${HEROKU_API_KEY}">~/.netrc
      env:
        EMAIL: ${{secrets.EMAIL_ORG}}
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push heroku `git subtree split --prefix backend master`:master --force
    - name: Frontend install
      run: npm install --prefix frontend
    - name: Github Pages Deploy
      run: npm run deploy
