name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/heroku@master"
        args : "container:login"
        env:
          HEROKU_API_KEY: {{secrets.HEROKU_API_KEY}}
      - uses: "actions/heroku@master"
        args: "container:push -a calm-fortress-1234 web"
        env:
          HEROKU_API_KEY: {{secrets.HEROKU_API_KEY}}
